name: dart_cloud_functions
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/robiness/dart-cloud-functions

environment:
  sdk: ^3.7.3

dependencies:
  shelf: ^1.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
